# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Chengyi Qin / Personal Homepage"
title_separator          : "-"
name                     : &name "Chengyi Qin"
description              : &description "Chengyi's academic portfolio"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://qinchengyi1.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile1.png"
  name             : "Chengyi Qin"
  pronouns         : # example: "she/her"  
  bio              : "PhD student @ Shandong University | Visiting @ SMU | Secret Sharing & MPC"
  location         : "Singapore / Jinan"
  employer         : "Shandong University Â· Visiting at SMU"
  uri              : # URL
  email            : "cyqin@mail.sdu.edu.cn" 
  links:
  - label: "Email (SDU)"
    icon: "fas fa-envelope"
    url: "mailto:cyqin@mail.sdu.edu.cn"
  - label: "Email (SMU)"
    icon: "fas fa-envelope"
    url: "mailto:cyqin@smu.edu.sg"
  - label: "Email (Personal)"
    icon: "fas fa-envelope"
    url: "mailto:qcy521111@163.com"




 
  # Social media
  #artstation       : # Username
  #bluesky          : "bsky.app" # Replace this with you Bluesky username
  #facebook         : # Username
  #flickr           : # Username
  #foursquare       : # Username
  #goodreads        : # Username
  #google_plus      : # Username
  #keybase          : # Username
  #instagram        : # Username
  #lastfm           : # Username
  #linkedin         : # Username
  #mastodon         : # URL
  #medium           : # URL
  #pinterest        : # Username
  #soundcloud       : # Username
  #steam            : # Username
  #telegram         : # URL
  #tumblr           : # Username
  #twitter          : # Username for X / Twitter
  #vine             : # Username
  #weibo            : # Username
  #wikipedia        : # Username
  #xing             : # Username
  #youtube          : # Username
  #zhihu            : # Username

# Publication Category - The following the list of publication categories and their headings
#publication_category:
  #books:
   # title: 'Books'
  #manuscripts:
    #title: 'Journal Articles'    
  #conferences:
   # title: 'Conference Papers'









